from Gramatica import Gramatica

def criar_gramatica_calabreso():
    """Cria a gramática completa da linguagem, já convertida para o formato LL(1)."""
    gramatica = Gramatica()

    gramatica.adicionar_producao('programa', ['lista_comandos'])
    gramatica.adicionar_producao('lista_comandos', ['comando', 'lista_comandos'])
    gramatica.adicionar_producao('lista_comandos', ['ε'])
    gramatica.adicionar_producao('bloco_comandos', ['LBRACE', 'lista_comandos', 'RBRACE'])
    gramatica.adicionar_producao('comando', ['declaracao', 'SEMICOLON'])
    gramatica.adicionar_producao('comando', ['comando_id', 'SEMICOLON'])
    gramatica.adicionar_producao('comando', ['comando_condicional'])
    gramatica.adicionar_producao('comando', ['comando_repeticao'])
    gramatica.adicionar_producao('comando', ['comando_io', 'SEMICOLON'])
    gramatica.adicionar_producao('comando', ['bloco_comandos'])
    gramatica.adicionar_producao('comando_id', ['ID', 'resto_comando_id'])
    gramatica.adicionar_producao('resto_comando_id', ['op_atribuicao', 'expressao'])
    gramatica.adicionar_producao('resto_comando_id', ['INCREMENTE'])
    gramatica.adicionar_producao('resto_comando_id', ['DECREMENTE'])
    gramatica.adicionar_producao('resto_comando_id', ['LPAREN', 'lista_argumentos', 'RPAREN'])
    gramatica.adicionar_producao('op_atribuicao', ['RECEBA'])
    gramatica.adicionar_producao('op_atribuicao', ['OP_ATRIBUICAO'])
    gramatica.adicionar_producao('lista_argumentos', ['lista_expressoes'])
    gramatica.adicionar_producao('lista_argumentos', ['ε'])

    gramatica.adicionar_producao('declaracao', ['prefixo_declaracao', 'tipo', 'ID', 'declaracao_opcional'])
    gramatica.adicionar_producao('prefixo_declaracao', ['DIGUE'])
    gramatica.adicionar_producao('prefixo_declaracao', ['ε']) 
    gramatica.adicionar_producao('declaracao_opcional', ['op_atribuicao', 'expressao'])
    gramatica.adicionar_producao('declaracao_opcional', ['LPAREN', 'lista_parametros', 'RPAREN', 'bloco_comandos'])
    gramatica.adicionar_producao('declaracao_opcional', ['ε'])
    gramatica.adicionar_producao('tipo', ['INTEGRO_TIPO'])
    gramatica.adicionar_producao('tipo', ['STRINGO_TIPO'])
    gramatica.adicionar_producao('tipo', ['REALO_TIPO'])
    gramatica.adicionar_producao('const_inicializacao_opcional', ['op_atribuicao', 'expressao'])
    gramatica.adicionar_producao('const_inicializacao_opcional', ['ε'])
    gramatica.adicionar_producao('declaracao_constante', ['DIGUE', 'tipo', 'ID', 'const_inicializacao_opcional'])

    gramatica.adicionar_producao('lista_parametros', ['parametro', 'lista_param_prime'])
    gramatica.adicionar_producao('lista_parametros', ['ε'])
    gramatica.adicionar_producao('lista_param_prime', ['COMMA', 'parametro', 'lista_param_prime'])
    gramatica.adicionar_producao('lista_param_prime', ['ε'])
    gramatica.adicionar_producao('parametro', ['tipo', 'ID'])

    gramatica.adicionar_producao('comando_condicional', ['IFO', 'LPAREN', 'expressao_logica', 'RPAREN', 'bloco_comandos', 'condicional_opcional'])
    gramatica.adicionar_producao('condicional_opcional', ['parte_elso_ifo'])
    gramatica.adicionar_producao('condicional_opcional', ['parte_else'])
    gramatica.adicionar_producao('condicional_opcional', ['ε'])
    gramatica.adicionar_producao('parte_elso_ifo', ['ELSO_IFO', 'LPAREN', 'expressao_logica', 'RPAREN', 'bloco_comandos', 'condicional_opcional'])
    gramatica.adicionar_producao('parte_else', ['ELSO', 'bloco_comandos'])

    gramatica.adicionar_producao('comando_repeticao', ['loop_duranto'])
    gramatica.adicionar_producao('comando_repeticao', ['loop_paro'])
    gramatica.adicionar_producao('loop_duranto', ['DURANTO', 'LPAREN', 'expressao_logica', 'RPAREN', 'bloco_comandos'])
    gramatica.adicionar_producao('loop_paro', ['PARO', 'LPAREN', 'atribuicao_simples', 'SEMICOLON', 'expressao_logica', 'SEMICOLON', 'passo_for', 'RPAREN', 'bloco_comandos'])
    gramatica.adicionar_producao('atribuicao_simples', ['ID', 'op_atribuicao', 'expressao_aritmetica'])
    gramatica.adicionar_producao('passo_for', ['ID', 'resto_passo_for'])
    gramatica.adicionar_producao('resto_passo_for', ['INCREMENTE'])
    gramatica.adicionar_producao('resto_passo_for', ['DECREMENTE'])
    gramatica.adicionar_producao('resto_passo_for', ['op_atribuicao', 'expressao_aritmetica'])

    gramatica.adicionar_producao('comando_io', ['CALMA', 'LPAREN', 'io_opcional', 'RPAREN'])
    gramatica.adicionar_producao('comando_io', ['CALABRESO', 'LPAREN', 'ID', 'RPAREN'])
    gramatica.adicionar_producao('io_opcional', ['lista_expressoes'])
    gramatica.adicionar_producao('io_opcional', ['ε'])
    gramatica.adicionar_producao('lista_expressoes', ['expressao', 'lista_exp_prime'])
    gramatica.adicionar_producao('lista_exp_prime', ['COMMA', 'expressao', 'lista_exp_prime'])
    gramatica.adicionar_producao('lista_exp_prime', ['ε'])

    gramatica.adicionar_producao('expressao', ['expressao_logica'])
    gramatica.adicionar_producao('expressao', ['STRINGO'])
    gramatica.adicionar_producao('expressao_logica', ['termo_logico', 'exp_log_prime'])
    gramatica.adicionar_producao('exp_log_prime', ['OP_OU', 'termo_logico', 'exp_log_prime'])
    gramatica.adicionar_producao('exp_log_prime', ['ε'])
    gramatica.adicionar_producao('termo_logico', ['expressao_relacional', 'termo_log_prime'])
    gramatica.adicionar_producao('termo_logico', ['OP_NEM', 'expressao_relacional'])
    gramatica.adicionar_producao('termo_log_prime', ['OP_E', 'expressao_relacional', 'termo_log_prime'])
    gramatica.adicionar_producao('termo_log_prime', ['ε'])
    gramatica.adicionar_producao('expressao_relacional', ['expressao_aritmetica', 'exp_rel_opcional'])
    gramatica.adicionar_producao('exp_rel_opcional', ['op_relacional', 'expressao_aritmetica'])
    gramatica.adicionar_producao('exp_rel_opcional', ['ε'])
    gramatica.adicionar_producao('op_relacional', ['OP_MAIOR_QUE'])
    gramatica.adicionar_producao('op_relacional', ['OP_MENOR_QUE'])
    gramatica.adicionar_producao('op_relacional', ['OP_MAIOR_INGUAL'])
    gramatica.adicionar_producao('op_relacional', ['OP_MENOR_INGUAL'])
    gramatica.adicionar_producao('op_relacional', ['OP_INGUAL'])
    gramatica.adicionar_producao('op_relacional', ['OP_VARIEGADO'])
    gramatica.adicionar_producao('expressao_aritmetica', ['termo', 'exp_arit_prime'])
    gramatica.adicionar_producao('exp_arit_prime', ['op_arit_soma', 'termo', 'exp_arit_prime'])
    gramatica.adicionar_producao('exp_arit_prime', ['ε'])
    gramatica.adicionar_producao('op_arit_soma', ['OP_MAIS'])
    gramatica.adicionar_producao('op_arit_soma', ['OP_MENOS'])
    gramatica.adicionar_producao('termo', ['fator', 'termo_prime'])
    gramatica.adicionar_producao('termo_prime', ['op_arit_mult', 'fator', 'termo_prime'])
    gramatica.adicionar_producao('termo_prime', ['ε'])
    gramatica.adicionar_producao('op_arit_mult', ['OP_MULTIPLIQUE'])
    gramatica.adicionar_producao('op_arit_mult', ['OP_DIVIDA'])
    gramatica.adicionar_producao('fator', ['INTEGRO'])
    gramatica.adicionar_producao('fator', ['REALO'])
    gramatica.adicionar_producao('fator', ['chamada_ou_variavel'])
    gramatica.adicionar_producao('fator', ['LPAREN', 'expressao', 'RPAREN'])
    gramatica.adicionar_producao('chamada_ou_variavel', ['ID', 'opt_chamada'])
    gramatica.adicionar_producao('opt_chamada', ['LPAREN', 'lista_argumentos', 'RPAREN'])
    gramatica.adicionar_producao('opt_chamada', ['ε'])

    gramatica.definir_simbolo_inicial('programa')

    return gramatica